import { MediaItem } from '@rntp/player';

export const playListData: MediaItem[] = [
  {
    mediaId: '1',
    title: 'Tajdar E Haram',
    artist: 'Hammad Nagri',
    albumTitle: 'Milad Naat 2026',
    artworkUrl: 'https://img.youtube.com/vi/J5IIjyk17SU/maxresdefault.jpg',
    url: require('./assets/audio/one.mp3') as string,
  },
  {
    mediaId: '2',
    title: 'Ya Nabi Muaj Pa Be Aik Nigahay Karam',
    artist: 'Hammad Ali Nagri',
    albumTitle: 'New Rabi ul Awal Naat 2025',
    artworkUrl: 'https://img.youtube.com/vi/49_eck_2nvI/maxresdefault.jpg',
    url: require('./assets/audio/two.mp3') as string,
  },
  {
    mediaId: '3',
    title: 'Ya Muhammad Sallay Ala (Qawwali)',
    artist: 'Sibtain Haider',
    albumTitle: 'TNA Records',
    artworkUrl: 'https://img.youtube.com/vi/p-Gj5Flj0Wk/maxresdefault.jpg',
    url: require('./assets/audio/three.mp3') as string,
  },
  {
    mediaId: '4',
    title: 'Aamad E Mustafa',
    artist: 'Gul e Zahra',
    albumTitle: 'Rabi ul Awal Kalam 2026',
    artworkUrl: 'https://img.youtube.com/vi/ID8jS0DK-qM/maxresdefault.jpg',
    url: require('./assets/audio/four.mp3') as string,
  },
  {
    mediaId: '5',
    title: 'Ankhon Mein Bas Gaya Hai Madina Huzoor Ka',
    artist: 'Armeena Aijaz',
    albumTitle: 'Rabi Ul Awal 2026 - TNA Records',
    artworkUrl: 'https://img.youtube.com/vi/vgvj32Vxe8s/maxresdefault.jpg',
    url: require('./assets/audio/five.mp3') as string,
  },
  {
    mediaId: '6',
    title: 'Mustafa Mustafa Aap Khair-ul-Bashar (Slowed & Reverb)',
    artist: 'Unknown Artist',
    albumTitle: 'Heart Touching Naat',
    artworkUrl: 'https://img.youtube.com/vi/syEl7yz6LNw/maxresdefault.jpg',
    url: require('./assets/audio/six.mp3') as string,
  },
  {
    mediaId: '7',
    title: 'Han Ali Ali',
    artist: 'Faizan Abbas',
    albumTitle: '13 Rajab Shina Manqabat 2024',
    artworkUrl: 'https://img.youtube.com/vi/mPqEhfyiml8/maxresdefault.jpg',
    url: require('./assets/audio/seven.mp3') as string,
  },
  {
    mediaId: '8',
    title: 'Wo Shehr E Mohabbat',
    artist: 'Syed Salih Jalali',
    albumTitle: 'New Rabiul Awwal Naat 2026',
    artworkUrl: 'https://img.youtube.com/vi/4OX_nOAPrY4/maxresdefault.jpg',
    url: require('./assets/audio/eight.mp3') as string,
  },
  {
    mediaId: '9',
    title: 'Mujh Pa Bhi Aik Karam',
    artist: 'Hammad Nagri / Danish Ammar',
    albumTitle: 'New Naat 2026 - Rabi ul Awal 2026',
    artworkUrl: 'https://img.youtube.com/vi/KP9zM2IFefQ/maxresdefault.jpg',
    url: require('./assets/audio/nine.mp3') as string,
  },
];